let parks = [{park: "Denali", location: "AL" },
{park: "Gates of the Artic", location: "AL" },
{park: "Glacier Bay", location: "AL" },
{park: "Katmai", location: "AL" },
{park: "Kenai Fjords", location: "AL" },
{park: "Kobuk Valley", location: "AL" },
{park: "Lake Clark", location: "AL" },
{park: "Wrangell - St. Elias", location: "AL" },
{park: "American Samoa", location: "American Samoa" },
{park: "Grand Canyon", location: "AZ" },
{park: "Petrified Forest", location: "Az" },
{park: "Saguaro", location: "AZ" },
{park: "Oregon Pipe Cactus", location: "AZ" },
{park: "Hot Springs", location: "AR" },
{park: "Channel Islands", location: "CA" },
{park: "Death Valley", location: "CA" },
{park: "Joshua Tree", location: "CA" },
{park: "Kings Canyon", location: "CA" },
{park: "Lassen Volcanic", location: "CA" },
{park: "Redwood", location: "CA" },
{park: "Sequoia", location: "CA" },
{park: "Yosemite", location: "CA" },
{park: "Black Canyon of the Gunnison", location: "CO" },
{park: "Great Sand Dunes", location: "CO" },
{park: "Mesa Verde", location: "CO" },
{park: "Rocky Mountain", location: "CO" },
{park: "Biscanye", location: "FL" },
{park: "Dry Tortugas", location: "FL" },
{park: "Everglades", location: "FL" },
{park: "Haleakala", location: "HI" },
{park: "Hawaii Volcanoes", location: "HI" },
{park: "Yellowstone", location: "ID" },
{park: "Mammoth Cave", location: "KY" },
{park: "Isle Royale", location: "MI" },
{park: "Voyageurs", location: "MN" },
{park: "Glacier", location: "MT" },
{park: "Great Basin", location: "NV" },
{park: "Carlsbad Caverns", location: "NM" },
{park: "Great Smoky Mountains", location: "NC" },
{park: "Theodore Roosevelt", location: "ND" },
{park: "Cuyahoga Valley", location: "OH" },
{park: "Crater Lake", location: "OR" },
{park: "Congaree", location: "SC" },
{park: "Badlands", location: "SD" },
{park: "Wind Cave", location: "SD" },
{park: "Big Bend", location: "TX" },
{park: "Guadalupe Mountains", location: "TX" },
{park: "Virgin Islands", location: "VI" },
{park: "Arches", location: "UT" },
{park: "Bryce Canyon", location: "UT" },
{park: "Canyonlands", location: "UT" },
{park: "Capital Reef", location: "UT" },
{park: "Zion", location: "UT" },
{park: "Shenandoah", location: "VA" },
{park: "Mount Rainier", location: "WA" },
{park: "North Cascades", location: "WA" },
{park: "Olympic", location: "WA" },
{park: "Grand Teton", location: "WY" },
]